version: "3.8"
services:
  frontend:
    build:
      context: ./task-manager-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./task-manager-backend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./task-manager-backend:/app
    environment:
      - NODE_ENV=development