name: Deploy to S3 and Serverless
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Frontend Setup
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Frontend Dependencies
        working-directory: ./task-manager-frontend
        run: npm install
      - name: Build React App
        working-directory: ./task-manager-frontend
        run: npm run build

      # Backend Setup
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Backend Dependencies
        working-directory: ./task-manager-backend
        run: |
          npm install
          pip install -r requirements.txt
      - name: Deploy Backend with Serverless
        working-directory: ./task-manager-backend
        run: npx serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      # AWS Config and Frontend Deploy
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync to S3
        run: aws s3 sync ./task-manager-frontend/dist/ s3://task-manager-web-bruno/
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
